language: node_js
node_js:
    - "10"
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
install:
    - yarn install
script:
    - yarn run pages
cache:
    directories:
        - "node_modules"
notifications:
    email: true
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: docs/
    github-token: $GITHUB_TOKEN
    repo: sibyl-vision/sibyl-web
    keep-history: true
    target-branch: master
    on:
        branch: master